services:
  backend:
    build: ./backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./backend
    command: celery -A sightline worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file: .env
    shm_size: '2gb'
    depends_on:
      - backend
      - redis

  celery_beat:
    build: ./backend
    command: celery -A sightline beat -l info
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - backend
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:7-alpine

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - backend

volumes:
  postgres_data:
