# Generated by Django 5.2.11 on 2026-02-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('lighthouse_json', models.JSONField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
