# Generated by Django 5.2.11 on 2026-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='network_type',
            field=models.CharField(choices=[('4g', '4G'), ('fast3g', 'Fast 3G'), ('slow3g', 'Slow 3G')], default='4g', max_length=10),
        ),
    ]
