# Generated by Django 6.0.2 on 2026-03-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_report_device_type_report_network_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
