# Generated by Django 5.2.12 on 2026-03-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_report_display_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='display_number',
        ),
    ]
